using Entities;
using Microsoft.EntityFrameworkCore;

namespace lern.Infrastructure;

public static class CategoryCatalogSeeder
{
    private sealed record CatalogNode(string Name, params CatalogNode[] Children);

    public static async Task SeedAsync(ShopDbContext db)
    {
        var roots = new[]
        {
            new CatalogNode("نخ",
                new CatalogNode("دوک نخ خیاطی", new CatalogNode("دوک نخ خیاطی سفید و مشکی"), new CatalogNode("نخ پلی استر رنگی"), new CatalogNode("نخ لی رنگی")),
                new CatalogNode("ماسوره نخ خیاطی", new CatalogNode("ماسوره نخ ۴۰۰ یارد"), new CatalogNode("ماسوره نخ ۴۰۰ یاردی رنگی"), new CatalogNode("ماسوره نخ طلقی"), new CatalogNode("ماسوره نخ لی"), new CatalogNode("ماسوره نخ دریما"), new CatalogNode("قرقره نخ ۱۰"), new CatalogNode("ماسوره نخ نایلون")),
                new CatalogNode("نخ استرج", new CatalogNode("دوک نخ استرج مشکی و سفید"), new CatalogNode("نخ استرج رنگی"), new CatalogNode("ماسوره نخ استرج")),
                new CatalogNode("نخ کوک", new CatalogNode("نخ کوک")), new CatalogNode("نخ ملحفه و نخ لحاف", new CatalogNode("نخ ملحفه دوزی - نخ لحاف")), new CatalogNode("نخ آرایشی", new CatalogNode("نخ آرایشی")), new CatalogNode("نخ عمامه", new CatalogNode("نخ عمامه")), new CatalogNode("نخ کوبلن - نخ گلدوزی", new CatalogNode("نخ کوبلن و نخ گلدوزی")), new CatalogNode("نخ نایلون قلاب بافی", new CatalogNode("نخ قلاب بافی سفید"), new CatalogNode("نخ قلاب بافی رنگی")), new CatalogNode("نخ لیف", new CatalogNode("نخ لیف")), new CatalogNode("نخ سرکیسه دوزی", new CatalogNode("نخ سر کیسه دوزی")), new CatalogNode("نخ نامرئی", new CatalogNode("نخ نامرئی")), new CatalogNode("نخ تسبیح", new CatalogNode("نخ تسبیح")), new CatalogNode("نخ گلابتون", new CatalogNode("نخ گلابتون")), new CatalogNode("نخ مرسریزه - نخ گیپور بافی", new CatalogNode("نخ مرسریزه - گیپور بافی")), new CatalogNode("نخ کنفی و گونی", new CatalogNode("نخ و طناب کنفی و گونی")), new CatalogNode("نخ رافیا", new CatalogNode("نخ کاغذی رافیا"))),
            new CatalogNode("سوزن",
                new CatalogNode("سوزن چرخ خیاطی", new CatalogNode("سوزن اچ آ - معمولی"), new CatalogNode("سوزن دی بی - راستادوز"), new CatalogNode("سوزن دی سی - سردوز یا زیگزاگ"), new CatalogNode("سوزن دی وی - میاندوز"), new CatalogNode("سوزن دی پی - جادکمه"), new CatalogNode("سوزن ژرسه"), new CatalogNode("سوزن دو قلو")),
                new CatalogNode("سوزن دستی خیاطی", new CatalogNode("سوزن رز"), new CatalogNode("سوزن دختری"), new CatalogNode("سوزن رویال"), new CatalogNode("سوزن سری و ته طلایی"), new CatalogNode("سوزن ملحفه دوزی"), new CatalogNode("سوزن لحاف دوزی"), new CatalogNode("سوزن تشک دوزی"), new CatalogNode("سوزن جوالدوز")),
                new CatalogNode("سوزن هنرهای دستی", new CatalogNode("سوزن روبان دوزی"), new CatalogNode("سوزن پته دوزی"), new CatalogNode("سوزن گلدوزی"), new CatalogNode("سوزن کوبلن"), new CatalogNode("سوزن منجق دوزی"), new CatalogNode("سوزن گونی بافی")), new CatalogNode("سوزن تحریر - ته مروارید", new CatalogNode("سوزن تحریر"), new CatalogNode("سوزن ته مروارید")), new CatalogNode("سنجاق قفلی", new CatalogNode("سنجاق قفلی")), new CatalogNode("سوزن نخ کن", new CatalogNode("سوزن نخ کن")), new CatalogNode("پونز", new CatalogNode("پونز"))),
            new CatalogNode("زیپ و متعلقات",
                new CatalogNode("زیپ ۲۰ سانت", new CatalogNode("زیپ دنده ۴ مشکی - سفید"), new CatalogNode("زیپ دنده ۳ مشکی و سفید"), new CatalogNode("زیپ دنده ۳ رنگی"), new CatalogNode("زیپ دنده ۴ رنگی"), new CatalogNode("زیپ دنده ۵ و دنده ۷")), new CatalogNode("زیپ نامرئی - مخفی", new CatalogNode("زیپ مخفی سفید و مشکی"), new CatalogNode("زیپ مخفی ۲۰ سانت رنگی"), new CatalogNode("زیپ مخفی ۵۰ و ۶۰ سانت دنده ۳"), new CatalogNode("زیپ مخفی ۲۰ سانت کتان"), new CatalogNode("زیپ مخفی ۵۰ سانت کتان")), new CatalogNode("زیپ لباسی", new CatalogNode("زیپ لباسی سفید و مشکی"), new CatalogNode("زیپ لباسی ۵۰ سانت رنگی")), new CatalogNode("زیپ دندانه فلزی", new CatalogNode("زیپ دندانه فلز کاپشنی"), new CatalogNode("زیپ دندانه فلز شلواری"), new CatalogNode("زیپ طرح دندانه فلزی")), new CatalogNode("زیپ دندانه لاکی", new CatalogNode("زیپ کاپشنی مشکی و سفید"), new CatalogNode("زیپ کاپشنی رنگی"), new CatalogNode("زیپ کاپشنی سیلور")), new CatalogNode("زیپ دندانه استخوانی", new CatalogNode("زیپ استخوانی مشکی و سفید"), new CatalogNode("زیپ کاپشنی استخوانی رنگی")), new CatalogNode("زیپ طاقه ای - متری - یکسره", new CatalogNode("زیپ طاقه ای متری مشکی - سفید"), new CatalogNode("زیپ طاقه ای متری رنگی")), new CatalogNode("ماشین زیپ - سری زیپ", new CatalogNode("سری زیپ پلاستیکی"), new CatalogNode("سری زیپ فلزی و کاپشنی"), new CatalogNode("سری زیپ استخوانی")), new CatalogNode("زیپ چسب", new CatalogNode("زیپ چسب باریک"), new CatalogNode("زیپ چسب پهن"))),
            new CatalogNode("قیچی و لوازم برش", new CatalogNode("قیچی آرایشی", new CatalogNode("قیچی آرایشی")), new CatalogNode("قیچی خیاطی", new CatalogNode("قیچی خیاطی لاکی"), new CatalogNode("قیچی ساووئی"), new CatalogNode("قیچی سینگر")), new CatalogNode("قیچی فاف", new CatalogNode("سایر قیچی های خیاطی لاکی"), new CatalogNode("سایر قیچی های خیاطی فلزی"), new CatalogNode("دسته قیچی")), new CatalogNode("قیچی دالبر", new CatalogNode("قیچی دالبر")), new CatalogNode("قیچی سرکج - سر صاف", new CatalogNode("قیچی سرکج و سر صاف و سر گرد")), new CatalogNode("قیچی سرنخ زن", new CatalogNode("قیچی سرنخ زن")), new CatalogNode("کاتر - تیز بر - موکت بر", new CatalogNode("کاتر - تیز بر")), new CatalogNode("قیچی کاغذ", new CatalogNode("قیچی کاغذ")), new CatalogNode("قیچی آشپزخانه و باغبانی", new CatalogNode("قیچی آشپزخانه و باغبانی")), new CatalogNode("قیچی تاشو")),
            new CatalogNode("لوازم خیاطی", new CatalogNode("محافظ کفی اتو - ابزار اتوکاری", new CatalogNode("اتو"), new CatalogNode("محافظ کفی اتو - آهن اتو"), new CatalogNode("میز اتو - پلاستیک و ژلاتین اتوکاری")), new CatalogNode("گونیا - خط کش", new CatalogNode("خط کش و شابلون خیاطی"), new CatalogNode("گونیا و پیستوله")), new CatalogNode("جعبه خیاطی", new CatalogNode("جعبه های خیاطی")), new CatalogNode("فن", new CatalogNode("فن دامنی"), new CatalogNode("فن شلواری - چهار تکه")), new CatalogNode("صابون", new CatalogNode("صابون و خودکار خیاطی")), new CatalogNode("سوزن خیاطی دستی", new CatalogNode("سوزن خیاطی دستی")), new CatalogNode("رولت خیاطی", new CatalogNode("رولت خیاطی")), new CatalogNode("کارگاه گلدوزی", new CatalogNode("کارگاه گلدوزی لاک و پلاستیکی"), new CatalogNode("کارگاه گلدوزی چوبی")), new CatalogNode("چوب کار", new CatalogNode("چوب کار - چوب لباسی")), new CatalogNode("دستگاه های اتیکت زن", new CatalogNode("تفنگ کارت زن"), new CatalogNode("تیبر و سوزن تفنگ کارت زن"), new CatalogNode("نخ پلیپ")), new CatalogNode("فنر و ژئون لباس عروس", new CatalogNode("فنر لباس و ژئون لباس عروس")), new CatalogNode("دستگاه های خیاطی", new CatalogNode("دستگاه های خیاطی")), new CatalogNode("ملزومات مغازه خیاطی", new CatalogNode("ترازو دیجیتال"), new CatalogNode("ملزومات مغازه خیاطی")), new CatalogNode("کلف لگو - کلکین - کلف رنگی", new CatalogNode("کلف برش"), new CatalogNode("کلف و مغفرا رنگی")), new CatalogNode("ابر - پشم شیشه", new CatalogNode("ابر"), new CatalogNode("پشم و شیشه - الیاف"))),
            new CatalogNode("لوازم چرخ خیاطی", new CatalogNode("پایه چرخ خیاطی", new CatalogNode("پایه چرخ معمولی"), new CatalogNode("پایه چرخ راستادوز"), new CatalogNode("پایه چین - پایه پلیسه"), new CatalogNode("پایه زیپ"), new CatalogNode("پایه لول"), new CatalogNode("پایه جادکمه"), new CatalogNode("پایه فودر"), new CatalogNode("پایه دوک")), new CatalogNode("ماکو چرخ خیاطی", new CatalogNode("ماکو چرخ معمولی"), new CatalogNode("ماکو چرخ راستادوز")), new CatalogNode("ماسوره چرخ خیاطی", new CatalogNode("ماسوره چرخ معمولی"), new CatalogNode("ماسوره چرخ راستادوز")), new CatalogNode("تسمه چرخ خیاطی", new CatalogNode("تسمه چرخ خیاطی")), new CatalogNode("روغن چرخ خیاطی", new CatalogNode("روغن چرخ خیاطی")), new CatalogNode("موتور چرخ خیاطی", new CatalogNode("موتور چرخ خیاطی")), new CatalogNode("لامپ چرخ خیاطی", new CatalogNode("لامپ چرخ خیاطی")), new CatalogNode("بیخ گوشتی چرخ خیاطی", new CatalogNode("بیخ گوشتی چرخ خیاطی")), new CatalogNode("پنس", new CatalogNode("پنس"))),
            new CatalogNode("مروارید - سرمه - منجق - تکه دوزی", new CatalogNode("مروارید", new CatalogNode("مروارید شماره ۳"), new CatalogNode("مروارید شماره ۴"), new CatalogNode("مروارید شماره ۵"), new CatalogNode("مروارید شماره ۶"), new CatalogNode("مروارید شماره ۸"), new CatalogNode("مروارید شماره ۱۰"), new CatalogNode("مروارید اشک"), new CatalogNode("مروارید گندمی"), new CatalogNode("مروارید پانچی"), new CatalogNode("مروارید رنگی و سنگی")), new CatalogNode("منجوق - مبله - پولک", new CatalogNode("منجوق گرد"), new CatalogNode("منجوق گرد درشت"), new CatalogNode("مبله ساده"), new CatalogNode("مبله بیج"), new CatalogNode("مبله شکسته"), new CatalogNode("پولک گرد"), new CatalogNode("پولک ریبانی و سکه ای"), new CatalogNode("پولک ستاره"), new CatalogNode("پولک برگی"), new CatalogNode("پولک طرح دار تزئینی")), new CatalogNode("گل های دوختنی و تزئینی", new CatalogNode("گل پفکی"), new CatalogNode("گل شکوفه"), new CatalogNode("گل و پاپیون تزئینی"), new CatalogNode("شکوفه نگین دار")), new CatalogNode("تکه دوزی و سرزانو و آرم", new CatalogNode("سرزانو - سرآنجی"), new CatalogNode("یقه آماده"), new CatalogNode("تکه دوزی عروسی"), new CatalogNode("تکه دوزی تزئینی"), new CatalogNode("تکه دوزی آرم و مارک"), new CatalogNode("آستین چادر ملی"), new CatalogNode("ساز لباس"), new CatalogNode("برچسب حرارتی و چاپی لباس")))
        };

        var existing = await db.Categories.ToDictionaryAsync(x => x.Name, StringComparer.Ordinal);
        var position = 0;
        foreach (var root in roots)
            await AddNodeAsync(root, null);

        async Task AddNodeAsync(CatalogNode node, int? parentId)
        {
            if (!existing.TryGetValue(node.Name, out var category))
            {
                category = new Category { Name = node.Name, Slug = $"catalog-{++position:D4}", ParentId = parentId, SortOrder = position };
                db.Categories.Add(category);
                await db.SaveChangesAsync();
                existing.Add(node.Name, category);
            }
            foreach (var child in node.Children)
                await AddNodeAsync(child, category.Id);
        }
    }
}
