SET XACT_ABORT ON;
BEGIN TRANSACTION;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/hardware-photo.png' WHERE Slug = N'buttons-and-hardware' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/thread-photo.png' WHERE Slug = N'catalog-0001' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/needles-photo.png' WHERE Slug = N'catalog-0040' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/zippers-photo.png' WHERE Slug = N'catalog-0071' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/scissors-photo.png' WHERE Slug = N'catalog-0108' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/sewing-tools-photo.png' WHERE Slug = N'catalog-0127' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/machine-tools-photo.png' WHERE Slug = N'catalog-0164' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/beads-photo.png' WHERE Slug = N'catalog-0186' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/elastic-photo.png' WHERE Slug = N'catalog-extra-000' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/curtain-photo.png' WHERE Slug = N'catalog-extra-020' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/yarn-photo.png' WHERE Slug = N'catalog-extra-026' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/ribbon-photo.png' WHERE Slug = N'catalog-extra-046' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/cord-photo.png' WHERE Slug = N'catalog-extra-086' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/snap-press-photo.png' WHERE Slug = N'catalog-extra-097' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/buttons-photo.png' WHERE Slug = N'catalog-extra-123' AND ParentId IS NULL AND ImageUrl IS NULL;
UPDATE dbo.categories SET ImageUrl = N'/assets/images/category/haberdashery/coat-buttons-photo.png' WHERE Slug = N'catalog-extra-147' AND ParentId IS NULL AND ImageUrl IS NULL;
COMMIT TRANSACTION;
