// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260429112547_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "شهر آرا"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ونک"
                        },
                        new
                        {
                            Id = 3,
                            Name = "سعادت آباد"
                        });
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisconType")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasDiscount")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Description = "core i7",
                            DisconType = 2,
                            Discount = 200000m,
                            HasDiscount = true,
                            Name = "لپ تاب",
                            Price = 2000000m
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 2,
                            Description = "redmi note 14",
                            DisconType = 2,
                            Discount = 200000m,
                            HasDiscount = true,
                            Name = "گوشی",
                            Price = 2000000m
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Description = "good",
                            DisconType = 2,
                            Discount = 200000m,
                            HasDiscount = true,
                            Name = "موس",
                            Price = 700000m
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 3,
                            Description = "همراه اول ",
                            DisconType = 1,
                            Discount = 10m,
                            HasDiscount = true,
                            Name = "مودم",
                            Price = 10000000m
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            Description = "17 pro max ",
                            DisconType = 2,
                            Discount = 200000m,
                            HasDiscount = true,
                            Name = "آیفون",
                            Price = 2000000m
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Description = "پرو",
                            DisconType = 1,
                            Discount = 15m,
                            HasDiscount = true,
                            Name = "ps5",
                            Price = 100000000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
